In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import pysentani as sti

In [2]:
survey = pd.read_excel('../data-anonymous/sentani-merged-cleaned-anonymous-2014-11-29.xlsx')

In order to compare survey data with metered data we want to look at specific villages. Here we will select for survey responses in Ajau which is powered by the PLN grid.

In [3]:
survey = survey[survey['village_name'] == 'Atamali']

* Two questions contained in the survey are:
    * survey['app_( )_per_wk']: For (appliance), how many times a week do you use it?
    * survey['app_( )_hrs']: For (appliance), each time you use it, how many hours do you use it for?

In [4]:
survey[['app_lighting_per_wk','app_lighting_hrs','app_TV_per_wk','app_TV_hrs',
        'app_radio_per_wk','app_radio_hrs','app_fridge_per_wk','app_fridge_hrs',
        'app_rice_cooker_per_wk','app_rice_cooker_hrs','app_fan_per_wk','app_fan_hrs']]

,app_lighting_per_wk,app_lighting_hrs,app_TV_per_wk,app_TV_hrs,app_radio_per_wk,app_radio_hrs,app_fridge_per_wk,app_fridge_hrs,app_rice_cooker_per_wk,app_rice_cooker_hrs,app_fan_per_wk,app_fan_hrs
152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,5,6,5,6,5,2,NaN,NaN,NaN,NaN,NaN,NaN
226,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,7,6,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN
259,7,7,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,7,6,7,6,NaN,NaN,NaN,NaN,7,2,7,2
261,7,6,7,6,7,1,NaN,NaN,NaN,NaN,NaN,NaN
262,5,6,5,6,7,3,NaN,NaN,NaN,NaN,NaN,NaN
264,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,7,6,7,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,5,6,5,6,6,5,NaN,NaN,NaN,NaN,NaN,NaN
301,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,NaN,NaN,7,6,7,6,NaN,NaN,7,1,NaN,NaN
395,7,6,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN
415,7,6,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN
416,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,7,6,7,6,NaN,NaN,NaN,NaN,7,6,7,6
518,7,6,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN
523,7,12,7,3,2,1,NaN,NaN,NaN,NaN,1,3
625,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,7,7,7,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
628,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668,3,6,7,6,NaN,NaN,NaN,NaN,7,6,NaN,NaN
669,7,6,7,2,2,3,NaN,NaN,NaN,NaN,NaN,NaN
670,5,6,5,2,7,6,NaN,NaN,3,1,NaN,NaN
671,5,6,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673,3,6,7,6,3,4,NaN,NaN,NaN,NaN,3,2
691,5,6,5,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,7,6,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
695,7,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
697,7,6,7,4,7,6,NaN,NaN,NaN,NaN,NaN,NaN
719,NaN,NaN,NaN,NaN,7,2,NaN,NaN,NaN,NaN,NaN,NaN

* Taking the product of these two columns will result in total hours used per week per appliance.
* Dividing the result by 7 will return an output of total appliance hours per day.
* The results are given new survey names and null responses filled in as zero's.

In [5]:
survey['daily_TV_hrs']     = (survey['app_TV_per_wk'] * survey['app_TV_hrs'])/7
survey['daily_fridge_hrs'] = (survey['app_fridge_per_wk'] * survey['app_fridge_hrs'])/7
survey['daily_radio_hrs']  = (survey['app_radio_per_wk'] * survey['app_radio_hrs'])/7
survey['daily_fan_hrs']    = (survey['app_fan_per_wk'] * survey['app_fan_hrs'])/7
survey['daily_rc_hrs']     = (survey['app_rice_cooker_per_wk'] * survey['app_rice_cooker_hrs'])/7
survey['daily_light_hrs']  = (survey['app_lighting_per_wk'] * survey['app_lighting_hrs'])/7

In [6]:
app_daily_hrs = survey[['daily_TV_hrs','daily_fridge_hrs','daily_radio_hrs',
                        'daily_fan_hrs','daily_rc_hrs','daily_light_hrs']]
app_daily_hrs.fillna(0)

,daily_TV_hrs,daily_fridge_hrs,daily_radio_hrs,daily_fan_hrs,daily_rc_hrs,daily_light_hrs
152,0.000000,0,0.000000,0.000000,0.000000,0.000000
225,4.285714,0,1.428571,0.000000,0.000000,4.285714
226,6.000000,0,0.000000,0.000000,0.000000,6.000000
228,6.000000,0,6.000000,0.000000,0.000000,6.000000
259,6.000000,0,0.000000,0.000000,0.000000,7.000000
260,6.000000,0,0.000000,2.000000,2.000000,6.000000
261,6.000000,0,1.000000,0.000000,0.000000,6.000000
262,4.285714,0,3.000000,0.000000,0.000000,4.285714
264,6.000000,0,0.000000,0.000000,0.000000,6.000000
266,6.000000,0,0.000000,0.000000,0.000000,6.000000
273,3.000000,0,0.000000,0.000000,0.000000,6.000000
274,4.285714,0,4.285714,0.000000,0.000000,4.285714
301,6.000000,0,0.000000,0.000000,0.000000,6.000000
342,6.000000,0,6.000000,0.000000,1.000000,0.000000
395,6.000000,0,6.000000,0.000000,0.000000,6.000000
415,6.000000,0,6.000000,0.000000,0.000000,6.000000
416,6.000000,0,0.000000,0.000000,0.000000,6.000000
417,6.000000,0,0.000000,0.000000,0.000000,6.000000
450,6.000000,0,0.000000,6.000000,6.000000,6.000000
518,6.000000,0,6.000000,0.000000,0.000000,6.000000
523,3.000000,0,0.285714,0.428571,0.000000,12.000000
625,6.000000,0,0.000000,0.000000,0.000000,6.000000
627,4.000000,0,0.000000,0.000000,0.000000,7.000000
628,6.000000,0,0.000000,0.000000,0.000000,6.000000
629,6.000000,0,0.000000,0.000000,0.000000,6.000000
668,6.000000,0,0.000000,0.000000,6.000000,2.571429
669,2.000000,0,0.857143,0.000000,0.000000,6.000000
670,1.428571,0,6.000000,0.000000,0.428571,4.285714
671,0.857143,0,0.000000,0.000000,0.000000,4.285714
673,6.000000,0,1.714286,0.857143,0.000000,2.571429
691,1.428571,0,0.000000,0.000000,0.000000,4.285714
694,6.000000,0,0.000000,0.000000,0.000000,6.000000
695,0.000000,0,0.000000,0.000000,0.000000,6.000000
697,4.000000,0,6.000000,0.000000,0.000000,6.000000
719,0.000000,0,2.000000,0.000000,0.000000,0.000000

45 minutes

Using a reference from consumer reports an amount of power will be assigned to each appliance:
https://www.consumerreports.org/cro/resources/images/video/wattage_calculator/wattage_calclulator.html
* currently a figure of 4 lightbulbs per energy access point will be used.
* rice cooker power was observed from models available to consumers as of this report.

|  Appliance 	|   Power	 |
|---------------|------------|
|   TV          | .200 kW    |
|   Fridge      | .725 kW    |
|   Radio       | .100 kW    |
|   Fan         | .135 kW    |
|   Rice Cooker | .700 kW    |
|   Lighting    | .100 kW x 4|

Now we have the amount of time the appliance is on each day and assigned power values for each, the daily energy can be found using the formula: $$Energy = power * time$$  
Units are in kWh.

In [7]:
survey['daily_TV_energy']     = survey['daily_TV_hrs']*.075
survey['daily_fridge_energy'] = survey['daily_fridge_hrs']*.200
survey['daily_radio_energy']  = survey['daily_radio_hrs']*.100
survey['daily_fan_energy']    = survey['daily_fan_hrs']*.135
survey['daily_rc_energy']     = survey['daily_rc_hrs']*.700
survey['daily_light_energy']  = survey['daily_light_hrs']*.400

In [8]:
app_daily_energy = survey[['daily_TV_energy','daily_fridge_energy','daily_radio_energy',
                        'daily_fan_energy','daily_rc_energy','daily_light_energy']]
app_daily_energy.fillna(0)

,daily_TV_energy,daily_fridge_energy,daily_radio_energy,daily_fan_energy,daily_rc_energy,daily_light_energy
152,0.000000,0,0.000000,0.000000,0.0,0.000000
225,0.321429,0,0.142857,0.000000,0.0,1.714286
226,0.450000,0,0.000000,0.000000,0.0,2.400000
228,0.450000,0,0.600000,0.000000,0.0,2.400000
259,0.450000,0,0.000000,0.000000,0.0,2.800000
260,0.450000,0,0.000000,0.270000,1.4,2.400000
261,0.450000,0,0.100000,0.000000,0.0,2.400000
262,0.321429,0,0.300000,0.000000,0.0,1.714286
264,0.450000,0,0.000000,0.000000,0.0,2.400000
266,0.450000,0,0.000000,0.000000,0.0,2.400000
273,0.225000,0,0.000000,0.000000,0.0,2.400000
274,0.321429,0,0.428571,0.000000,0.0,1.714286
301,0.450000,0,0.000000,0.000000,0.0,2.400000
342,0.450000,0,0.600000,0.000000,0.7,0.000000
395,0.450000,0,0.600000,0.000000,0.0,2.400000
415,0.450000,0,0.600000,0.000000,0.0,2.400000
416,0.450000,0,0.000000,0.000000,0.0,2.400000
417,0.450000,0,0.000000,0.000000,0.0,2.400000
450,0.450000,0,0.000000,0.810000,4.2,2.400000
518,0.450000,0,0.600000,0.000000,0.0,2.400000
523,0.225000,0,0.028571,0.057857,0.0,4.800000
625,0.450000,0,0.000000,0.000000,0.0,2.400000
627,0.300000,0,0.000000,0.000000,0.0,2.800000
628,0.450000,0,0.000000,0.000000,0.0,2.400000
629,0.450000,0,0.000000,0.000000,0.0,2.400000
668,0.450000,0,0.000000,0.000000,4.2,1.028571
669,0.150000,0,0.085714,0.000000,0.0,2.400000
670,0.107143,0,0.600000,0.000000,0.3,1.714286
671,0.064286,0,0.000000,0.000000,0.0,1.714286
673,0.450000,0,0.171429,0.115714,0.0,1.028571
691,0.107143,0,0.000000,0.000000,0.0,1.714286
694,0.450000,0,0.000000,0.000000,0.0,2.400000
695,0.000000,0,0.000000,0.000000,0.0,2.400000
697,0.300000,0,0.600000,0.000000,0.0,2.400000
719,0.000000,0,0.200000,0.000000,0.0,0.000000

In [9]:
app_daily_energy.sum()

daily_TV_energy        11.892857
daily_fridge_energy          NaN
daily_radio_energy      5.657143
daily_fan_energy        1.253571
daily_rc_energy        10.800000
daily_light_energy     73.142857
dtype: float64

In [10]:
app_daily_energy.sum().sum()/35

2.9356122448979591